services:

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: "pg_isready -h postgres"
      interval: 3s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile_uv
      target: dev
      args:
        enviroment: ${ENVIROMENT:-dev}
    command: make run
    volumes:
      # - .:/workspace
      - ./backend:/app
      - ./database/migrations:/app/migrations
      - ./database/alembic.ini:/app/alembic.ini
      - ./database/database.py:/app/src/database.py
      - ./database/models.py:/app/src/api/models.py
    depends_on:
      postgres:
        condition: service_healthy

  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
      target: build
    command: tail -f /dev/null
    volumes:
      - ./nuxt:/app
    ports:
      - 3000:3000
