name: cleanup

on: [workflow_call]

env:
  TEST_DIR: test_dir

jobs:
  litter_up:
    name: Generating empty files and folders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Litter with empty files and folders
        run: |
          mkdir -p ./$TEST_DIR/qwe/asd/zxc
          touch ./$TEST_DIR/qwe/asd ./$TEST_DIR/qwe/asd/asd ./$TEST_DIR/qwe/asd/zxc/zxc
